### PR TITLE
made button clickable and converted input to array

### PR DESCRIPTION
**Pull request by sadiethongsavanh**

### CODE REVIEW

**Review by JesseDenier — CHANGES_REQUESTED** [review]
Sadie this looks great, and worked almost perfectly on my end when copied and tested locally!

Here are my notes for changes that may make it easier to keep track of as we build it out.

Line 2 - Add notation for lines 3-5.
Line 3 - Change "submitB" to "searchBtn"
Line 4 - Change "inputB" to "userIngredientInput"
Line 5 - Change "arrayB" to "ingredientArray"
Line 6 - Add a space between 5 and 6 and notation for the click event function.

Lines 8-10 - This works for console logging what the user entered, but its creating a new array called "inputValueB when you want it to be populating "arrayB/ingredientArray". This can be fixed by changing "let inputValueB" to just "ingredientArray"
Line 8-10 - Lastly I would add notation to what line 8 and then what line 9 does so we understand. We may want to change " " to ", " so that the user can separate their ingredients with a comma.

**Review by eimonto22 — APPROVED** [review]
approve for minor changes for user input into an array.

**Comment by sadiethongsavanh** [comment]
Changes have been made per request

**Review by JesseDenier — APPROVED** [review]
Looks great. Now we need to set the API fetches to use this input and run their functions after the button press.

**Pull request merged**
